name: Run script on new JSON

on:
  push:
    paths:
      - 'events/*.json'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get list of new files
        run: |
          echo "new_files=$(git diff --name-only --diff-filter=A HEAD^ HEAD | xargs -I {} printf '\"%s\" ' {})" >> $GITHUB_ENV

      - name: Run script
        run: |
          if [[ -n "${{ env.new_files }}" ]]; then
            python add_event.py ${{ env.new_files }}
          fi
        env:
          EVENTBRITE_API_TOKEN: ${{ secrets.EVENTBRITE_API_TOKEN }}
          EVENTBRITE_ORGANIZATION_ID: ${{ secrets.EVENTBRITE_ORGANIZATION_ID }}
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
